baseURL = "https://phgelado.com/me/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Hi this is Pedro! 👋"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

# Automatically set last modified dates using Git commit dates
enableGitInfo = true

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/phgelado"
    weight = 4
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  # Description to display on homepage
  description = "I work deploying AI systems to tackle complex problems."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#FF4D4D"

  # Display "back to top" button on posts and pages
  ShowBackToTopButton = true

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = ""

  # Defines number of posts displayed on homepage if showPostsOnHomePage option is set
  # Default value is 4
  numberPostsOnHomePage = 4

  # Configure how post dates are displayed
  # dateFormat must be set if lastmod is declared in front matter, or enableGitInfo
  # is true
  dateFormat = "January 2, 2006"

  # Footer text
  footer = "Pedro Hernandez Gelado"

  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/phgelado/"},
    {name = "stackoverflow", url = "https://stackoverflow.com/users/23576190/pedro-hernandez-gelado"},
    {name = "youtube", url = "https://www.youtube.com/@periquitopedro"},
    {name = "twitter", url = "https://x.com/phgelado"},
  ]